Homework 4.1
netology-code/and-homeworks pull request #9
Opened 2019-03-14 16:18 UTC by tpom6oh

Хочется добавить про ViewHolder и RecyclerView в 4 раздел, поэтому тут сразу про адаптер, в 4.2 будет про манипуляции контентом списка - удаление и pull to refresh, в 4.3 свой адаптер с ViewHolder'ом, в 4.4 замена ListView на RecyclerView.

2019-03-16 09:59 UTC, gordinmitya requested changes
в целом по идее хранить приложеньку прям тут – с гитхаба нельзя скачать одну папку, подразумевается что ребята будут выкачивать всю репу с домашками?

есть документ концепт по практикам, там на 4ый блок отводиться 2 занятия, ты как я понял хочешь сделать 4?
сам я двумя руками за то чтобы рассказать про recyclerview и pullToRefresh, ты согласовал измнения?

2019-03-16 09:59 UTC, gordinmitya commented on 4.1.listview/Readme.md
> +2. Добавьте ConstraintLayout в `app/build.gradle`. (`implementation 'com.android.support:design:28.0.0'`)
ConstraintLayout подключается через
`implementation 'com.android.support.constraint:constraint-layout:1.1.2'`

2019-03-16 09:59 UTC, gordinmitya commented on 4.1.listview/Readme.md
> +3. Создайте xml файл в папке `res/layout` для элемента списка на основе ConstraintLayout, состоящий из двух TextView, один под другим.
Constraint тяжеловат для того чтобы с его помощью один TextView под другим расположить. Лучше LinearLayout использовать

2019-03-16 09:59 UTC, gordinmitya commented on 4.1.listview/Readme.md
> +3. Создайте xml файл в папке `res/layout` для элемента списка на основе ConstraintLayout, состоящий из двух TextView, один под другим.
вообще есть готовая разметка для элемента списка с двумя TextView, или ты хочешь научить именно custom делать?

2019-03-16 09:59 UTC, gordinmitya commented on 4.1.listview/Readme.md
> +5. В метоже createAdapter измените входной параметр на `List<Map<String, String>>` и создайте `SimpleAdapter` вместо `ArrayAdapter`.
опечатка, методе

2019-03-16 09:59 UTC, gordinmitya commented on 4.1.listview/code/app/build.gradle
> +    implementation 'com.android.support:appcompat-v7:28.0.0'
в чате обсуждаем сейчас чему учить, стоит ли давать задания на support
по идее он доживает свои последние дни и когда ребята закончат учиться будет обновляться только androidx

2019-03-17 17:49 UTC, tpom6oh commented on 4.1.listview/Readme.md
> +2. Добавьте ConstraintLayout в `app/build.gradle`. (`implementation 'com.android.support:design:28.0.0'`)
👍

2019-03-17 17:54 UTC, tpom6oh commented
Можно вынести код в отдельный репозиторий, я взял эту идею из методички, как обычно делают в Нетологии?

Все еще думаю уложиться в 2 занятия. Вот что получается: 
https://hackmd.io/s/HJ4Ut-hDV
https://hackmd.io/s/rJyif-nwV

2019-03-17 17:57 UTC, tpom6oh commented on 4.1.listview/Readme.md
> +3. Создайте xml файл в папке `res/layout` для элемента списка на основе ConstraintLayout, состоящий из двух TextView, один под другим.
Идея в том, чтобы студенты как можно больше работали с ConstraintLayout, и чувствовали себя свободно для его постоянного использования.

2019-03-17 20:49 UTC, tpom6oh commented on 4.1.listview/Readme.md
> +5. В метоже createAdapter измените входной параметр на `List<Map<String, String>>` и создайте `SimpleAdapter` вместо `ArrayAdapter`.
Спасибо

2019-03-17 20:49 UTC, tpom6oh commented on 4.1.listview/code/app/build.gradle
> +    implementation 'com.android.support:appcompat-v7:28.0.0'
На мой взгляд сразу давать androidx это хорошая идея.

2019-03-18 09:48 UTC, ArtemPervushow commented on 4.1.listview/Readme.md
> +В этом домашнем задании дается стартовое приложение, которое показывает список строк простейшим образом. Вам нужно переписать его, используя класс SimpleAdapter и добавить подзаголовок.
Добавь мотивацию пожалуйста. Пару предложений вроде "Списки в мобильном приложении- самая часто используемая фича" и т.д.

2019-03-18 09:48 UTC, ArtemPervushow commented on 4.1.listview/Readme.md
> +* Вместо `ArrayAdapter` создать `SimpleAdapter`.
Вместо чего? Просто напиши создать SimpleAdapter

2019-03-18 09:49 UTC, ArtemPervushow commented on 4.1.listview/Readme.md
> +* Использовать создынный адаптер в списке
Опечатка

2019-03-18 09:50 UTC, ArtemPervushow commented on 4.1.listview/Readme.md
> +3. Создайте xml файл в папке `res/layout` для элемента списка на основе ConstraintLayout, состоящий из двух TextView, один под другим.
На данном этапе у слушателей нет информации о ConstraintLayout. Поэтому пишем LinearLayout. Хотя идея понятна и приветствуется

2019-03-18 09:51 UTC, ArtemPervushow commented on 4.1.listview/Readme.md
> +В качестве заголовка используем элемент массива строк из ориганального приложения, подзаголовком будет длина этой строки.
Либо упрощаем фразу, либо нужен пример кода

2019-03-18 11:49 UTC, tpom6oh commented on 4.1.listview/Readme.md
> +3. Создайте xml файл в папке `res/layout` для элемента списка на основе ConstraintLayout, состоящий из двух TextView, один под другим.
А в 3.2 разве не планируется рассказать про ConstraintLayout?

2019-03-18 11:51 UTC, tpom6oh commented on 4.1.listview/Readme.md
> +* Вместо `ArrayAdapter` создать `SimpleAdapter`.
В исходном приложении есть метод createAdapter, из которого надо вместо ArrayAdapter вернуть SimpleAdapter, распишу это подробнее

2019-03-18 11:52 UTC, tpom6oh commented on 4.1.listview/Readme.md
> +* Использовать создынный адаптер в списке
👍

2019-03-18 11:53 UTC, tpom6oh commented on 4.1.listview/Readme.md
> +В качестве заголовка используем элемент массива строк из ориганального приложения, подзаголовком будет длина этой строки.
понял, доработаю

2019-03-23 11:02 UTC, tpom6oh commented on 4.1.listview/Readme.md
> +3. Создайте xml файл в папке `res/layout` для элемента списка на основе ConstraintLayout, состоящий из двух TextView, один под другим.
Вот тут https://github.com/netology-code/and-homeworks/tree/master/3.2.OtherLayouts/3.2.1, может все-таки оставим ConstraintLayout?

2019-03-29 09:22 UTC, merged